[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s" 