# API Keys
FRED_API_KEY = "dceb19d6ccadfb4115c3ac2493b7d5ed"
FINNHUB_API_KEY = "cuvuqk9r01qub8tvp140cuvuqk9r01qub8tvp14g"
NEWSAPI_KEY = "5fdb5ee6296948ffa091cf9a0b50b819"
MARKETAUX_KEY = "XVhI7gTkFhKVBMywSBb19p4kpXEhnwDz1b8lSTJ1"
ALPHA_VANTAGE_KEY = "9ODUKBW8F70DZQQE"
TRADEFILTER_KEY = "05b9cc401d354a1da097058150b24b88ad1b3ddc7ec0491e9114499c14dc18c0"

# Rate Limits (requests per minute)
ALPHA_VANTAGE_RATE_LIMIT = 5
FRED_RATE_LIMIT = 120
FINNHUB_RATE_LIMIT = 60
NEWSAPI_RATE_LIMIT = 100
MARKETAUX_RATE_LIMIT = 50

# Cache Configuration
CACHE_DURATION = 3600  # in seconds

# Data Refresh Settings
DATA_REFRESH_INTERVAL = 300  # 5 minutes in seconds
HISTORICAL_DATA_REFRESH = 86400  # 24 hours in seconds
NEWS_REFRESH_INTERVAL = 900  # 15 minutes in seconds
SENTIMENT_REFRESH_INTERVAL = 1800  # 30 minutes in seconds

# Retry Configuration
MAX_RETRIES = 3
RETRY_DELAY = 2  # seconds
TIMEOUT = 10  # seconds 